// Generated by `ecg-eval fit-vf --gbdt`. Do not edit by hand.
//
// Empty on purpose. A tree ensemble has been fitted and measured against the
// linear model on the held-out third twice, and was worse both times: AUC 0.876
// against 0.889 on six features, and 0.864 against 0.894 on nine. It is not
// better, so it is not shipped. The path stays so the comparison can be
// repeated, and it has been.
pub const VENTRICULAR_FIBRILLATION: GbdtModel = GbdtModel::EMPTY;
