// Generated by `ecg-eval fit-vf --gbdt`. Do not edit by hand.
//
// Empty on purpose. A tree ensemble was fitted and measured against the linear
// model on the held-out third: AUC 0.876 against 0.889. It is not better, so it
// is not shipped. The path stays so the comparison can be repeated.
pub const VENTRICULAR_FIBRILLATION: GbdtModel = GbdtModel::EMPTY;
